### PR TITLE
Update efl license info and dependencies

### PR DESCRIPTION
**Pull request by optarg**
Plus some other minor clean up.

### CODE REVIEW

**Comment by NuLogicSystems** [comment]
Making changes like these are why the upstream packages for this suck..

**Comment by optarg** [comment]
I never made openjpeg optional. You must have misread the diff. As for openjpeg(1) still being required to build efl, that's news to me. I suppose I need to be more diligent about checking what does and doesn't get pulled into my chroot.

As for wayland-protocols, enlightenment's meson build does check for it. Under the assumption that it is a make dependency, I added it because it's possible that someone might have built efl but then removed wayland-protocols. I'm suprised to hear it's a runtime dependency given what the package contains, but I'll change this back.

And I'm well aware that you're a close follower of the Enlightenment project. On the rare occasion I do drop by #e, you always seem to be there. This is why I use these PKGBUILDs. I didn't mean to step on any toes.

**Comment by NuLogicSystems** [comment]
No problems. I'm actually not sure about wayland-protocols myself, I'm asking now.
But the issue with openjpeg is the satble releases are always updated from the corresponding branch, not from master. In the 1.20 branch evas loaders are still using openjpeg (version one). The commit that ported it is only in master (1.20.999999 aka 1.21)

**Comment by optarg** [comment]
I removed the offending changes. How you want to handle wayland-protocols is up to you.

**Comment by NuLogicSystems** [comment]
Yea, Simotek is looking into it.

**Comment by NuLogicSystems** [comment]
Cool, I'll go ahead and merge then. Once Simotek finishes his review of the wayland-protocols issue I'll do what needs to be done. ;)

**Pull request merged**
